export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const CONTINUE_PURCHASING = "CONTINUE_PURCHASING";
export const CANCEL_PURCHASING = "CANCEL_PURCHASING";
export const IS_NAVIGATION_VISIBLE = "IS_NAVIGATION_VISIBLE";
export const IS_NAVIGATION_STICKY = "IS_NAVIGATION_STICKY";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CONTINUE_SIGNING = "CONTINUE_SIGNING";
export const CANCEL_SIGNING = "CANCEL_SIGNING";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GET_ADDRESS_DATA = "GET_ADDRESS_DATA";
export const GET_ADDRESS_DATA_START = "GET_ADDRESS_DATA_START";
export const GET_ADDRESS_DATA_SUCCESS = "GET_ADDRESS_DATA_SUCCESS";
export const GET_ADDRESS_DATA_FAIL = "GET_ADDRESS_DATA_FAIL";

export const REVEAL_BACKDROP = "REVEAL_BACKDROP";
export const HIDE_BACKDROP = "HIDE_BACKDROP";

export const SUBMIT_PERSONAL_INFO = "SUBMIT_PERSONAL_INFO";
export const SUBMIT_PERSONAL_INFO_START = "SUBMIT_PERSONAL_INFO_START";
export const SUBMIT_PERSONAL_INFO_SUCCESS = "SUBMIT_PERSONAL_INFO_SUCCESS";
export const SUBMIT_PERSONAL_INFO_FAIL = "SUBMIT_PERSONAL_INFO_FAIL";
